/**
 * Static demo dataset for the Universal Asset Search.
 *
 * 50 well-known US-listed assets covering all GICS sectors. Prices, YTD returns,
 * and market caps are PLAUSIBLE BUT DEMO VALUES — never quote these to a client.
 *
 * Shariah flag mirrors the curated list in shariah-compliant-assets.json, except
 * the cross-cutting rules are encoded here as `shariahReason` strings so the
 * detail drawer can explain WHY a name was excluded (e.g., interest-based revenue
 * for banks, primary-business exclusions for alcohol/tobacco/gambling, etc.).
 *
 * Replace this whole file with a live Finnhub + Shariah board feed in production.
 */

import type { Asset } from "./types";
import { metricsFor } from "./metrics";

const RAW_ASSETS: Asset[] = [
  // ─── Tech (Shariah-compliant) ─────────────────────────────────────────────
  { symbol: "AAPL",  nameEn: "Apple Inc.",            nameAr: "آبل",              assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 232.45, priceChangePct: 0.42,  ytdReturn: 18.2,  marketCapUsd: 3520, peRatio: 32.4, dividendYield: 0.43, high52: 245.10, low52: 168.20, shariahCompliant: true },
  { symbol: "MSFT",  nameEn: "Microsoft Corp.",       nameAr: "مايكروسوفت",       assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 445.32, priceChangePct: -0.18, ytdReturn: 11.4,  marketCapUsd: 3310, peRatio: 35.1, dividendYield: 0.72, high52: 467.50, low52: 366.50, shariahCompliant: true },
  { symbol: "GOOGL", nameEn: "Alphabet Inc. (Class A)", nameAr: "ألفابت (جوجل)",   assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 182.65, priceChangePct: 1.12,  ytdReturn: 22.6,  marketCapUsd: 2270, peRatio: 26.8, dividendYield: 0.45, high52: 195.80, low52: 130.40, shariahCompliant: true },
  { symbol: "NVDA",  nameEn: "NVIDIA Corp.",          nameAr: "إنفيديا",          assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 138.45, priceChangePct: 2.10,  ytdReturn: 95.4,  marketCapUsd: 3380, peRatio: 64.5, dividendYield: 0.02, high52: 152.90, low52: 78.50,  shariahCompliant: true },
  { symbol: "ADBE",  nameEn: "Adobe Inc.",            nameAr: "أدوبي",            assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 545.20, priceChangePct: 0.65,  ytdReturn: 7.8,   marketCapUsd: 243,  peRatio: 41.0, high52: 638.50, low52: 488.20, shariahCompliant: true },
  { symbol: "CRM",   nameEn: "Salesforce Inc.",       nameAr: "سيلزفورس",         assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 312.80, priceChangePct: -0.42, ytdReturn: 14.5,  marketCapUsd: 305,  peRatio: 47.2, high52: 348.20, low52: 226.40, shariahCompliant: true },
  { symbol: "ORCL",  nameEn: "Oracle Corp.",          nameAr: "أوراكل",           assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 168.45, priceChangePct: 0.88,  ytdReturn: 24.6,  marketCapUsd: 468,  peRatio: 38.4, dividendYield: 0.95, high52: 192.40, low52: 110.20, shariahCompliant: true },
  { symbol: "AMD",   nameEn: "Advanced Micro Devices", nameAr: "إيه إم دي",       assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 158.30, priceChangePct: 1.55,  ytdReturn: 18.9,  marketCapUsd: 256,  peRatio: 51.0, high52: 187.20, low52: 116.50, shariahCompliant: true },
  { symbol: "CSCO",  nameEn: "Cisco Systems Inc.",    nameAr: "سيسكو",            assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 58.40,  priceChangePct: 0.21,  ytdReturn: 12.4,  marketCapUsd: 232,  peRatio: 22.0, dividendYield: 2.78, high52: 62.85,  low52: 45.50,  shariahCompliant: true },
  { symbol: "AVGO",  nameEn: "Broadcom Inc.",         nameAr: "برودكوم",          assetClass: "stock", sector: "tech",                  region: "us", currency: "USD", lastPrice: 178.20, priceChangePct: 2.40,  ytdReturn: 56.8,  marketCapUsd: 832,  peRatio: 78.2, dividendYield: 1.18, high52: 196.40, low52: 110.20, shariahCompliant: true },

  // ─── Healthcare (Shariah-compliant) ──────────────────────────────────────
  { symbol: "JNJ",   nameEn: "Johnson & Johnson",     nameAr: "جونسون آند جونسون", assetClass: "stock", sector: "healthcare",            region: "us", currency: "USD", lastPrice: 162.85, priceChangePct: -0.15, ytdReturn: 12.2,  marketCapUsd: 392,  peRatio: 24.5, dividendYield: 3.06, high52: 168.20, low52: 142.50, shariahCompliant: true },
  { symbol: "LLY",   nameEn: "Eli Lilly & Co.",       nameAr: "إيلاي ليلي",        assetClass: "stock", sector: "healthcare",            region: "us", currency: "USD", lastPrice: 798.50, priceChangePct: 0.92,  ytdReturn: 31.5,  marketCapUsd: 758,  peRatio: 78.0, dividendYield: 0.65, high52: 968.40, low52: 605.20, shariahCompliant: true },
  { symbol: "ABBV",  nameEn: "AbbVie Inc.",           nameAr: "أبفي",             assetClass: "stock", sector: "healthcare",            region: "us", currency: "USD", lastPrice: 198.40, priceChangePct: 0.32,  ytdReturn: 14.6,  marketCapUsd: 350,  peRatio: 24.8, dividendYield: 3.32, high52: 212.30, low52: 166.40, shariahCompliant: true },
  { symbol: "MRK",   nameEn: "Merck & Co. Inc.",      nameAr: "ميرك",             assetClass: "stock", sector: "healthcare",            region: "us", currency: "USD", lastPrice: 110.25, priceChangePct: -0.40, ytdReturn: 6.8,   marketCapUsd: 280,  peRatio: 20.5, dividendYield: 2.96, high52: 128.20, low52: 99.50,  shariahCompliant: true },
  { symbol: "PFE",   nameEn: "Pfizer Inc.",           nameAr: "فايزر",            assetClass: "stock", sector: "healthcare",            region: "us", currency: "USD", lastPrice: 28.75,  priceChangePct: 0.08,  ytdReturn: 4.2,   marketCapUsd: 162,  peRatio: 12.5, dividendYield: 6.05, high52: 31.40,  low52: 25.20,  shariahCompliant: true },
  { symbol: "ABT",   nameEn: "Abbott Laboratories",   nameAr: "أبوت",             assetClass: "stock", sector: "healthcare",            region: "us", currency: "USD", lastPrice: 118.60, priceChangePct: 0.55,  ytdReturn: 16.2,  marketCapUsd: 206,  peRatio: 33.0, dividendYield: 1.92, high52: 124.50, low52: 95.20,  shariahCompliant: true },

  // ─── Consumer (Shariah-compliant) ────────────────────────────────────────
  { symbol: "NKE",   nameEn: "Nike Inc.",             nameAr: "نايكي",            assetClass: "stock", sector: "consumer_discretionary", region: "us", currency: "USD", lastPrice: 76.20,  priceChangePct: -0.95, ytdReturn: -8.4,  marketCapUsd: 114,  peRatio: 25.8, dividendYield: 2.10, high52: 96.20,  low52: 70.10,  shariahCompliant: true },
  { symbol: "COST",  nameEn: "Costco Wholesale",      nameAr: "كوستكو",           assetClass: "stock", sector: "consumer_staples",      region: "us", currency: "USD", lastPrice: 902.45, priceChangePct: 0.65,  ytdReturn: 28.5,  marketCapUsd: 400,  peRatio: 55.2, dividendYield: 0.50, high52: 958.20, low52: 658.40, shariahCompliant: true },
  { symbol: "PG",    nameEn: "Procter & Gamble",      nameAr: "بروكتر آند جامبل",  assetClass: "stock", sector: "consumer_staples",      region: "us", currency: "USD", lastPrice: 174.85, priceChangePct: 0.12,  ytdReturn: 8.6,   marketCapUsd: 412,  peRatio: 27.8, dividendYield: 2.32, high52: 178.40, low52: 152.20, shariahCompliant: true },
  { symbol: "HD",    nameEn: "Home Depot",            nameAr: "هوم ديبوت",        assetClass: "stock", sector: "consumer_discretionary", region: "us", currency: "USD", lastPrice: 408.60, priceChangePct: 0.34,  ytdReturn: 5.6,   marketCapUsd: 405,  peRatio: 26.2, dividendYield: 2.20, high52: 425.20, low52: 326.50, shariahCompliant: true },
  { symbol: "LOW",   nameEn: "Lowe's Companies",      nameAr: "لويز",             assetClass: "stock", sector: "consumer_discretionary", region: "us", currency: "USD", lastPrice: 262.40, priceChangePct: 0.71,  ytdReturn: 6.2,   marketCapUsd: 148,  peRatio: 21.5, dividendYield: 1.78, high52: 287.50, low52: 218.40, shariahCompliant: true },

  // ─── Industrials / Energy / Materials / Communication (Shariah-compliant) ─
  { symbol: "CAT",   nameEn: "Caterpillar Inc.",      nameAr: "كاتربيلر",         assetClass: "stock", sector: "industrials",           region: "us", currency: "USD", lastPrice: 388.20, priceChangePct: 1.08,  ytdReturn: 14.8,  marketCapUsd: 184,  peRatio: 17.5, dividendYield: 1.55, high52: 418.50, low52: 286.40, shariahCompliant: true },
  { symbol: "DE",    nameEn: "Deere & Co.",           nameAr: "ديري",             assetClass: "stock", sector: "industrials",           region: "us", currency: "USD", lastPrice: 425.30, priceChangePct: -0.42, ytdReturn: 4.5,   marketCapUsd: 116,  peRatio: 15.8, dividendYield: 1.45, high52: 472.40, low52: 358.20, shariahCompliant: true },
  { symbol: "XOM",   nameEn: "Exxon Mobil",           nameAr: "إكسون موبيل",      assetClass: "stock", sector: "energy",                region: "us", currency: "USD", lastPrice: 118.40, priceChangePct: 0.25,  ytdReturn: 10.8,  marketCapUsd: 522,  peRatio: 14.2, dividendYield: 3.40, high52: 126.20, low52: 95.40,  shariahCompliant: true },
  { symbol: "CVX",   nameEn: "Chevron Corp.",         nameAr: "شيفرون",           assetClass: "stock", sector: "energy",                region: "us", currency: "USD", lastPrice: 162.50, priceChangePct: -0.28, ytdReturn: 8.2,   marketCapUsd: 296,  peRatio: 16.4, dividendYield: 4.20, high52: 170.20, low52: 132.40, shariahCompliant: true },
  { symbol: "LIN",   nameEn: "Linde plc",             nameAr: "ليندي",            assetClass: "stock", sector: "materials",             region: "us", currency: "USD", lastPrice: 468.20, priceChangePct: 0.18,  ytdReturn: 12.4,  marketCapUsd: 221,  peRatio: 32.8, dividendYield: 1.30, high52: 487.50, low52: 388.20, shariahCompliant: true },
  { symbol: "TMUS",  nameEn: "T-Mobile US Inc.",      nameAr: "تي موبايل",        assetClass: "stock", sector: "communication",         region: "us", currency: "USD", lastPrice: 215.80, priceChangePct: 0.42,  ytdReturn: 16.5,  marketCapUsd: 254,  peRatio: 24.6, dividendYield: 1.62, high52: 226.40, low52: 162.40, shariahCompliant: true },

  // ─── Shariah ETFs ─────────────────────────────────────────────────────────
  { symbol: "SPUS",  nameEn: "SP Funds S&P 500 Shariah ETF", nameAr: "صندوق إس بي للأسهم الأمريكية المتوافقة", assetClass: "etf", sector: "diversified", region: "us", currency: "USD", lastPrice: 47.95, priceChangePct: 0.32, ytdReturn: 17.1, marketCapUsd: 1.2, peRatio: 28.4, dividendYield: 0.85, high52: 49.20, low52: 38.40, shariahCompliant: true },
  { symbol: "HLAL",  nameEn: "Wahed FTSE USA Shariah ETF",   nameAr: "صندوق واحد للأسهم الأمريكية المتوافقة",   assetClass: "etf", sector: "diversified", region: "us", currency: "USD", lastPrice: 48.40, priceChangePct: 0.28, ytdReturn: 16.5, marketCapUsd: 0.6, peRatio: 27.8, dividendYield: 0.92, high52: 49.80, low52: 39.20, shariahCompliant: true },
  { symbol: "SPSK",  nameEn: "SP Funds Dow Jones Global Sukuk ETF", nameAr: "صندوق إس بي للصكوك العالمية",     assetClass: "etf", sector: "diversified", region: "global", currency: "USD", lastPrice: 21.45, priceChangePct: -0.05, ytdReturn: 4.0, marketCapUsd: 0.3, dividendYield: 4.20, high52: 22.10, low52: 20.15, shariahCompliant: true },

  // ─── Financials (excluded — interest-based revenue) ──────────────────────
  { symbol: "JPM",   nameEn: "JPMorgan Chase",        nameAr: "جي بي مورغان",     assetClass: "stock", sector: "financials",            region: "us", currency: "USD", lastPrice: 235.80, priceChangePct: -0.42, ytdReturn: 28.4,  marketCapUsd: 666, peRatio: 12.5, dividendYield: 2.10, high52: 248.40, low52: 178.20, shariahCompliant: false, shariahReason: "Primary business is conventional banking — interest-based revenue exceeds the 5% Shariah screen." },
  { symbol: "BAC",   nameEn: "Bank of America",       nameAr: "بنك أوف أمريكا",   assetClass: "stock", sector: "financials",            region: "us", currency: "USD", lastPrice: 45.85,  priceChangePct: -0.18, ytdReturn: 14.2,  marketCapUsd: 354, peRatio: 13.8, dividendYield: 2.32, high52: 48.20,  low52: 35.40,  shariahCompliant: false, shariahReason: "Conventional bank — interest-based revenue exceeds the 5% Shariah screen." },
  { symbol: "WFC",   nameEn: "Wells Fargo",           nameAr: "ويلز فارجو",       assetClass: "stock", sector: "financials",            region: "us", currency: "USD", lastPrice: 76.40,  priceChangePct: 0.15,  ytdReturn: 11.8,  marketCapUsd: 261, peRatio: 12.4, dividendYield: 2.10, high52: 81.50,  low52: 56.20,  shariahCompliant: false, shariahReason: "Conventional bank — interest-based revenue exceeds the 5% Shariah screen." },
  { symbol: "GS",    nameEn: "Goldman Sachs Group",   nameAr: "جولدمان ساكس",     assetClass: "stock", sector: "financials",            region: "us", currency: "USD", lastPrice: 562.40, priceChangePct: 0.62,  ytdReturn: 16.4,  marketCapUsd: 180, peRatio: 14.2, dividendYield: 2.10, high52: 595.20, low52: 425.40, shariahCompliant: false, shariahReason: "Investment bank — interest-based revenue and excessive leverage exceed Shariah screens." },
  { symbol: "C",     nameEn: "Citigroup Inc.",        nameAr: "سيتي جروب",        assetClass: "stock", sector: "financials",            region: "us", currency: "USD", lastPrice: 78.20,  priceChangePct: -0.32, ytdReturn: 21.4,  marketCapUsd: 148, peRatio: 11.8, dividendYield: 2.85, high52: 82.40,  low52: 58.20,  shariahCompliant: false, shariahReason: "Conventional bank — interest-based revenue exceeds the 5% Shariah screen." },
  { symbol: "BRK.B", nameEn: "Berkshire Hathaway B",  nameAr: "بيركشاير هاثاواي",  assetClass: "stock", sector: "financials",            region: "us", currency: "USD", lastPrice: 482.50, priceChangePct: 0.15,  ytdReturn: 12.2,  marketCapUsd: 1042, peRatio: 18.5, high52: 498.40, low52: 408.20, shariahCompliant: false, shariahReason: "Significant insurance subsidiary revenue and conventional investment income." },

  // ─── Tobacco / alcohol / gambling (excluded — primary business) ──────────
  { symbol: "MO",    nameEn: "Altria Group",          nameAr: "ألتريا",           assetClass: "stock", sector: "consumer_staples",      region: "us", currency: "USD", lastPrice: 55.20,  priceChangePct: 0.10,  ytdReturn: 12.4,  marketCapUsd: 93,   peRatio: 9.8,  dividendYield: 7.42, high52: 58.40,  low52: 41.20,  shariahCompliant: false, shariahReason: "Primary business is tobacco — categorically non-permissible." },
  { symbol: "PM",    nameEn: "Philip Morris Intl.",   nameAr: "فيليب موريس",       assetClass: "stock", sector: "consumer_staples",      region: "us", currency: "USD", lastPrice: 132.40, priceChangePct: -0.22, ytdReturn: 11.5,  marketCapUsd: 206,  peRatio: 18.6, dividendYield: 4.15, high52: 138.50, low52: 92.40,  shariahCompliant: false, shariahReason: "Primary business is tobacco — categorically non-permissible." },
  { symbol: "BUD",   nameEn: "Anheuser-Busch InBev",  nameAr: "أنهيوزر بوش",       assetClass: "stock", sector: "consumer_staples",      region: "europe", currency: "USD", lastPrice: 62.80, priceChangePct: 0.40, ytdReturn: 2.8, marketCapUsd: 124, peRatio: 18.2, dividendYield: 1.45, high52: 68.50, low52: 56.20, shariahCompliant: false, shariahReason: "Primary business is alcoholic beverages — categorically non-permissible." },
  { symbol: "LVS",   nameEn: "Las Vegas Sands",       nameAr: "لاس فيجاس ساندز",  assetClass: "stock", sector: "consumer_discretionary", region: "us", currency: "USD", lastPrice: 52.40,  priceChangePct: -0.65, ytdReturn: -8.5,  marketCapUsd: 38,   peRatio: 25.4, dividendYield: 1.92, high52: 58.40,  low52: 41.20,  shariahCompliant: false, shariahReason: "Primary business is casino gambling — categorically non-permissible." },

  // ─── Mixed / debt-heavy / entertainment (excluded by ratio screens) ──────
  { symbol: "TSLA",  nameEn: "Tesla Inc.",            nameAr: "تيسلا",            assetClass: "stock", sector: "consumer_discretionary", region: "us", currency: "USD", lastPrice: 248.50, priceChangePct: 2.85,  ytdReturn: -8.2,  marketCapUsd: 790,  peRatio: 78.4, high52: 365.20, low52: 188.40, shariahCompliant: false, shariahReason: "Debt-to-market-cap ratio exceeds the 33% Shariah screen due to recent financing rounds." },
  { symbol: "AMZN",  nameEn: "Amazon.com Inc.",       nameAr: "أمازون",           assetClass: "stock", sector: "consumer_discretionary", region: "us", currency: "USD", lastPrice: 218.40, priceChangePct: 0.85,  ytdReturn: 18.4,  marketCapUsd: 2280, peRatio: 42.5, high52: 232.40, low52: 156.20, shariahCompliant: false, shariahReason: "AWS financing arm + interest-bearing securities push interest income above the 5% screen." },
  { symbol: "NFLX",  nameEn: "Netflix Inc.",          nameAr: "نتفليكس",          assetClass: "stock", sector: "communication",         region: "us", currency: "USD", lastPrice: 818.40, priceChangePct: 1.45,  ytdReturn: 38.4,  marketCapUsd: 351,  peRatio: 48.5, high52: 905.50, low52: 480.40, shariahCompliant: false, shariahReason: "Entertainment content overlap with non-permissible categories; debt ratio exceeds screen." },
  { symbol: "DIS",   nameEn: "Walt Disney Co.",       nameAr: "ديزني",            assetClass: "stock", sector: "communication",         region: "us", currency: "USD", lastPrice: 105.80, priceChangePct: -0.45, ytdReturn: -5.2,  marketCapUsd: 192,  peRatio: 38.2, dividendYield: 0.95, high52: 122.40, low52: 86.20,  shariahCompliant: false, shariahReason: "Significant interest-bearing debt and content portfolio overlapping non-permissible categories." },
  { symbol: "KO",    nameEn: "Coca-Cola Co.",         nameAr: "كوكاكولا",         assetClass: "stock", sector: "consumer_staples",      region: "us", currency: "USD", lastPrice: 68.20,  priceChangePct: 0.18,  ytdReturn: 9.8,   marketCapUsd: 294,  peRatio: 25.4, dividendYield: 2.85, high52: 73.50,  low52: 58.40,  shariahCompliant: false, shariahReason: "Debt ratio exceeds the 33% Shariah screen and interest income above the 5% threshold." },
  { symbol: "BA",    nameEn: "Boeing Co.",            nameAr: "بوينج",            assetClass: "stock", sector: "industrials",           region: "us", currency: "USD", lastPrice: 168.40, priceChangePct: -1.20, ytdReturn: -5.4,  marketCapUsd: 102,  peRatio: 0,    high52: 196.40, low52: 142.50, shariahCompliant: false, shariahReason: "Defense revenue mix + debt ratio exceeds the 33% Shariah screen." },

  // ─── Utilities (Shariah-compliant) ───────────────────────────────────────
  { symbol: "NEE",   nameEn: "NextEra Energy",        nameAr: "نيكست إيرا للطاقة",  assetClass: "stock", sector: "utilities",             region: "us", currency: "USD", lastPrice: 78.40,  priceChangePct: 0.62,  ytdReturn: 9.4,   marketCapUsd: 161,  peRatio: 22.5, dividendYield: 2.84, high52: 86.20,  low52: 64.50,  shariahCompliant: true },
  { symbol: "DUK",   nameEn: "Duke Energy",           nameAr: "دوك للطاقة",          assetClass: "stock", sector: "utilities",             region: "us", currency: "USD", lastPrice: 118.20, priceChangePct: -0.18, ytdReturn: 6.8,   marketCapUsd: 92,   peRatio: 20.2, dividendYield: 3.65, high52: 124.40, low52: 96.20,  shariahCompliant: true },
  { symbol: "SO",    nameEn: "Southern Co.",          nameAr: "ساوذرن للطاقة",       assetClass: "stock", sector: "utilities",             region: "us", currency: "USD", lastPrice: 92.40,  priceChangePct: 0.32,  ytdReturn: 12.4,  marketCapUsd: 101,  peRatio: 21.8, dividendYield: 3.18, high52: 95.20,  low52: 72.40,  shariahCompliant: true },

  // ─── Real Estate / REITs (Shariah-compliant) ─────────────────────────────
  { symbol: "PLD",   nameEn: "Prologis Inc.",         nameAr: "بروليجيس للعقارات",   assetClass: "stock", sector: "real_estate",           region: "us", currency: "USD", lastPrice: 122.40, priceChangePct: 1.08,  ytdReturn: 4.2,   marketCapUsd: 113,  peRatio: 35.8, dividendYield: 3.24, high52: 138.50, low52: 102.40, shariahCompliant: true },
  { symbol: "AMT",   nameEn: "American Tower",        nameAr: "أميركان تاور",        assetClass: "stock", sector: "real_estate",           region: "us", currency: "USD", lastPrice: 218.40, priceChangePct: -0.42, ytdReturn: -2.6,  marketCapUsd: 102,  peRatio: 28.5, dividendYield: 3.05, high52: 245.20, low52: 198.20, shariahCompliant: true },
  { symbol: "O",     nameEn: "Realty Income Corp.",   nameAr: "ريالتي إنكم",         assetClass: "stock", sector: "real_estate",           region: "us", currency: "USD", lastPrice: 58.40,  priceChangePct: 0.18,  ytdReturn: 2.8,   marketCapUsd: 53,   peRatio: 32.4, dividendYield: 5.42, high52: 62.40,  low52: 50.20,  shariahCompliant: true },

  // ─── Broad index ETFs (excluded — mixed holdings include financials) ─────
  { symbol: "SPY",   nameEn: "SPDR S&P 500 ETF",      nameAr: "صندوق إس بي 500",   assetClass: "etf", sector: "diversified",           region: "us", currency: "USD", lastPrice: 612.85, priceChangePct: 0.42, ytdReturn: 18.2, marketCapUsd: 612, peRatio: 28.5, dividendYield: 1.25, high52: 625.40, low52: 488.20, shariahCompliant: false, shariahReason: "S&P 500 includes financials, alcohol, and tobacco names that fail Shariah screens." },
  { symbol: "QQQ",   nameEn: "Invesco QQQ Trust",     nameAr: "صندوق إنفيسكو كيو", assetClass: "etf", sector: "tech",                  region: "us", currency: "USD", lastPrice: 524.40, priceChangePct: 0.85, ytdReturn: 24.8, marketCapUsd: 312, peRatio: 35.4, dividendYield: 0.55, high52: 545.20, low52: 408.40, shariahCompliant: false, shariahReason: "Nasdaq-100 includes names with non-permissible revenue streams." },
  { symbol: "VOO",   nameEn: "Vanguard S&P 500 ETF",  nameAr: "صندوق فانغارد 500", assetClass: "etf", sector: "diversified",           region: "us", currency: "USD", lastPrice: 561.20, priceChangePct: 0.40, ytdReturn: 18.1, marketCapUsd: 575, peRatio: 28.4, dividendYield: 1.28, high52: 572.40, low52: 446.50, shariahCompliant: false, shariahReason: "Same S&P 500 holdings — fails Shariah screens." },
  { symbol: "AGG",   nameEn: "iShares Core U.S. Aggregate Bond ETF", nameAr: "صندوق آي شيرز للسندات", assetClass: "etf", sector: "diversified", region: "us", currency: "USD", lastPrice: 98.25, priceChangePct: -0.12, ytdReturn: 2.4, marketCapUsd: 118, dividendYield: 4.10, high52: 100.40, low52: 94.20, shariahCompliant: false, shariahReason: "Conventional interest-bearing bonds — categorically non-permissible." },
];

// Merge computed metrics (1Y / 3Y return, 1Y volatility) onto every asset that
// has a series in `optimizer/historical-data.json`. Assets without a series
// keep `undefined` — the UI shows an em-dash.
export const ASSETS: Asset[] = RAW_ASSETS.map((a) => ({ ...a, ...metricsFor(a.symbol) }));

export const ASSETS_BY_SYMBOL: Map<string, Asset> = new Map(
  ASSETS.map((a) => [a.symbol, a]),
);
